#!/usr/bin/env python3
"""
Spotify OAuth2 setup helper for the Omarchy Spotify Mini Player plugin.

Usage:
    python3 ~/.config/omarchy/plugins/spotify/setup.py
"""

import base64
import hashlib
import http.server
import json
import secrets
import socket
import sys
import urllib.parse
import urllib.request
import webbrowser
from pathlib import Path

DEFAULT_REDIRECT_URI = "http://127.0.0.1:18923/callback"
CREDENTIALS_DIR = Path.home() / ".config" / "omarchy" / "spotify"
CREDENTIALS_FILE = CREDENTIALS_DIR / "credentials.env"
SCOPES = "user-read-currently-playing user-read-playback-state user-modify-playback-state"


def header(text):
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")


def step(text):
    print(f"  → {text}")


def generate_pkce():
    verifier = secrets.token_urlsafe(64)[:128]
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return verifier, challenge


def exchange_code(client_id, client_secret, code, code_verifier, redirect_uri):
    data = urllib.parse.urlencode({
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": redirect_uri,
        "client_id": client_id,
        "code_verifier": code_verifier,
    }).encode("ascii")

    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    if client_secret:
        auth = base64.b64encode(f"{client_id}:{client_secret}".encode()).decode()
        headers["Authorization"] = f"Basic {auth}"

    req = urllib.request.Request(
        "https://accounts.spotify.com/api/token", data=data, headers=headers
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def save_credentials(client_id, client_secret, refresh_token):
    CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
    from datetime import datetime
    content = f"""# Spotify Mini Player Credentials
# Generated by setup.py on {datetime.now().isoformat()}
# Do not edit manually — re-run setup.py to regenerate

SPOTIFY_CLIENT_ID={client_id}
SPOTIFY_CLIENT_SECRET={client_secret}
SPOTIFY_REFRESH_TOKEN={refresh_token}
"""
    CREDENTIALS_FILE.write_text(content)
    CREDENTIALS_FILE.chmod(0o600)


def extract_code(text):
    """Pull the authorization code out of a pasted URL or bare code."""
    text = text.strip()
    if not text:
        return None
    if "://" in text or "?" in text:
        params = urllib.parse.parse_qs(urllib.parse.urlparse(text).query)
        if "code" in params:
            return params["code"][0]
        return None
    return text  # bare code pasted directly


class CallbackHandler(http.server.BaseHTTPRequestHandler):
    auth_code = None

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        params = urllib.parse.parse_qs(parsed.query)

        if "code" in params:
            CallbackHandler.auth_code = params["code"][0]
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(b"""
                <html><body style="font-family:system-ui;max-width:500px;margin:50px auto;text-align:center">
                <h2>&#10004; Authorization successful!</h2>
                <p>You can close this tab and return to the terminal.</p>
                </body></html>
            """)
        else:
            error = params.get("error", ["unknown"])[0]
            self.send_response(400)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(f"""
                <html><body style="font-family:system-ui;max-width:500px;margin:50px auto;text-align:center">
                <h2>&#10008; Authorization failed: {error}</h2>
                </body></html>
            """.encode())

    def log_message(self, format, *args):
        pass


def wait_for_callback(host, port):
    server = http.server.HTTPServer((host, port), CallbackHandler)
    server.timeout = 180
    step("Waiting for authorization in browser...")
    while CallbackHandler.auth_code is None:
        server.handle_request()
    code = CallbackHandler.auth_code
    CallbackHandler.auth_code = None
    server.server_close()
    return code


def check_port(host, port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind((host, port))
            return True
        except OSError:
            return False


def main():
    header("Spotify Mini Player — Setup")

    print("  This widget shows your currently playing Spotify track")
    print("  in the Omarchy topbar. It works with any device playing")
    print("  on your Spotify account (phone, other computer, etc.).")
    print()

    # Step 1: Create Spotify App
    print("Step 1: Create a Spotify Developer App")
    print("-" * 40)
    print()
    print("  1. Open: https://developer.spotify.com/dashboard")
    print("  2. Click 'Create App'")
    print("  3. Fill in any app name and description")
    print("  4. As Redirect URI, try:")
    print(f"       {DEFAULT_REDIRECT_URI}")
    print("     (Spotify allows plain HTTP for 127.0.0.1 loopback addresses.)")
    print("     If the dashboard refuses to save that, use any HTTPS URL")
    print("     instead, e.g.:  https://example.com/callback")
    print("  5. Check the 'Web API' checkbox and click 'Save'")
    print()

    client_id = input("  Spotify Client ID: ").strip()
    if not client_id:
        print("  ✗ Client ID is required.")
        sys.exit(1)

    client_secret = input("  Spotify Client Secret (leave empty if none): ").strip()

    redirect_uri = input(f"  Redirect URI you registered [{DEFAULT_REDIRECT_URI}]: ").strip()
    if not redirect_uri:
        redirect_uri = DEFAULT_REDIRECT_URI
    redirect_uri = redirect_uri.rstrip("/") if redirect_uri.endswith("/callback/") else redirect_uri

    parsed = urllib.parse.urlparse(redirect_uri)
    loopback = parsed.scheme == "http" and parsed.hostname in ("127.0.0.1", "::1") and parsed.port

    # Step 2: Authorization
    print(f"\nStep 2: Authorize the App")
    print("-" * 40)

    if loopback and not check_port(parsed.hostname, parsed.port):
        print(f"\n  ✗ Port {parsed.port} is in use. Close other processes and retry.")
        sys.exit(1)

    code_verifier, code_challenge = generate_pkce()

    auth_url = (
        "https://accounts.spotify.com/authorize?"
        f"client_id={client_id}"
        "&response_type=code"
        f"&redirect_uri={urllib.parse.quote(redirect_uri)}"
        f"&scope={urllib.parse.quote(SCOPES)}"
        "&code_challenge_method=S256"
        f"&code_challenge={code_challenge}"
    )

    step("Opening browser for authorization...")
    print()
    print("  If the browser didn't open, visit this URL:")
    print()
    print(f"  {auth_url}")
    print()

    try:
        webbrowser.open(auth_url)
    except Exception:
        pass

    if loopback:
        code = wait_for_callback(parsed.hostname, parsed.port)
        if not code:
            print("  ✗ No authorization code received.")
            sys.exit(1)
    else:
        print("  After you click 'Agree', the browser will redirect to")
        print(f"  {redirect_uri}?code=...")
        print("  The page itself will NOT load — that's expected!")
        print("  Copy the FULL URL from the address bar and paste it here.")
        print()
        code = None
        while code is None:
            pasted = input("  Paste the redirect URL here: ")
            code = extract_code(pasted)
            if code is None:
                print("  ✗ No 'code' found in that URL — paste the complete address-bar URL.")

    step("Authorization code received!")

    # Step 3: Exchange for tokens
    print(f"\nStep 3: Saving credentials")
    print("-" * 40)

    try:
        token_data = exchange_code(client_id, client_secret, code, code_verifier, redirect_uri)
    except Exception as e:
        print(f"  ✗ Token exchange failed: {e}")
        sys.exit(1)

    refresh_token = token_data.get("refresh_token")
    if not refresh_token:
        print("  ✗ No refresh token received. Check your app permissions.")
        sys.exit(1)

    save_credentials(client_id, client_secret, refresh_token)

    print(f"\n{'='*60}")
    print(f"  ✓ Setup complete!")
    print(f"{'='*60}")
    print()
    print(f"  Credentials saved to: {CREDENTIALS_FILE}")
    print()
    print("  The widget is already in your bar layout.")
    print("  It will appear once Spotify starts playing something.")
    print()
    print("  To reconfigure, run: python3 ~/.config/omarchy/plugins/spotify/setup.py")
    print()


if __name__ == "__main__":
    main()
